apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraform-mcp.fullname" . }}-svc
  labels:
    {{- include "terraform-mcp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "terraform-mcp.selectorLabels" . | nindent 4 }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    name: http
