{{- if and .Values.certificate.enabled .Values.ingress.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  labels:
    {{- include "hashicorp-mcp.labels" . | nindent 4 }}
spec:
  secretName: {{ .Values.ingress.tls.secretName }}
  commonName: {{ .Values.certificate.commonName }}
  dnsNames:
    - {{ .Values.certificate.commonName }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
{{- end }}
